apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-d
  template:
    metadata:
      labels:
        app: app-d
    spec:
      containers:
        - image: wbitt/network-multitool
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nginx-index-file
              mountPath: /usr/share/nginx/html/
          name: network-multitool
      volumes:
      - name: nginx-index-file
        configMap:
          name: index-html-configmap
      initContainers:
      - name: init-app-d
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]